<?php

require_once('flowadmin.devicetypes.inc');
require_once('flowadmin.topics.inc');
require_once('flowadmin.datastores.inc');

/**
 * Implements hook_init()
 * 
 */
function flowadmin_init()
{
	
}

/**
 * Implementation of hook_menu
 */
function flowadmin_menu()
{
	$items = array();
	$items += _flowadmin_menu_devicetypes();
	$items += _flowadmin_menu_topics();
	$items += _flowadmin_menu_datastores(); 
	
	return $items;
}

/**
 * Implements hook_theme()
 */
function flowadmin_theme($existing, $type, $theme, $path)
{
	$themes = array();
	$themes += _flowadmin_theme_devicetypes();
	$themes += _flowadmin_theme_topics();
	$themes += _flowadmin_theme_datastores();
	
	return $themes;
}

/**
 * Determine if a user should be given access to a menu item or not
 */
function flowadmin_access()
{
	if (flowautho_show_flowadmin_menu_item()) 
	{
		return true;
	}
	else
	{
		flowadmin_set_permissions_error_message(true);
		drupal_goto('<front>');
	}
}

function flowadmin_set_permissions_error_message($cache = false)
{
	$message = t('You do not have sufficient permission to access this resource.');
	flowautho_set_message('c-ate-flowadmin-permissions-error', $message, 'error', $cache);	
}

/**
 * Implementation of hook__preprocess_page
 * 
 * @param unknown_type $variables
 */
function flowadmin_preprocess_page(&$variables)
{
	if (strpos(current_path(), FLOWADMIN) !== FALSE) 
	{
		 // This disables message-printing on ALL page displays
		  $variables['show_messages'] = FALSE;
	}	
}

/**
 * Implements of hook_jstemplates
 */
function flowadmin_jstemplates()
{
	$templates = array();
	

	$templates[] = '<div id="topic-delete-warning-template" data-modalid="topic-delete-warning"  class="modal fade c-popup c-ate-modal-delete-topic-warning">'
				. '	<div class="modal-dialog">'
				. '		<div class="modal-content">'
				. '			<div class="modal-header">'
				. '				<button type="button" class="close c-ate-delete-topic-warning-cancel" data-dismiss="modal" aria-hidden="true">&times;</button>'
				. '				<h4 class="modal-title">Delete topic</h4>'
				. '			</div>'
				. '			<div class="modal-body">'
				. '				<p>Please confirm that you wish to delete this FlowMessaging topic.</p>'
				. '			</div>'
				. '			<div class="modal-footer">'
				. '				<button type="button" class="btn btn-dashboard-default c-ate-delete-topic-warning-cancel-button c-cancel-btn" data-dismiss="modal">Cancel</button>'
				. '				<button type="button" class="btn btn-danger c-ate-delete-topic-warning-confirm-button c-continue-btn">Delete</button>'
				. '			</div>'
				. '		</div>'
				. '	</div>'
				. '</div>';	
				
	

	$templates[] = '<div id="datastore-delete-warning-template" data-modalid="datastore-delete-warning"  class="modal fade c-popup c-ate-modal-delete-datastore-warning">'
				. '	<div class="modal-dialog">'
				. '		<div class="modal-content">'
				. '			<div class="modal-header">'
				. '				<button type="button" class="close c-ate-delete-datastore-warning-cancel" data-dismiss="modal" aria-hidden="true">&times;</button>'
				. '				<h4 class="modal-title">Delete datastore</h4>'
				. '			</div>'
				. '			<div class="modal-body">'
				. '				<p>Please confirm that you wish to delete this datastore.</p>'
				. '			</div>'
				. '			<div class="modal-footer">'
				. '				<button type="button" class="btn btn-dashboard-default c-ate-delete-datastore-warning-cancel-button c-cancel-btn" data-dismiss="modal">Cancel</button>'
				. '				<button type="button" class="btn btn-danger c-ate-delete-datastore-warning-confirm-button c-continue-btn">Delete</button>'
				. '			</div>'
				. '		</div>'
				. '	</div>'
				. '</div>';					
		
	return $templates;
}
    